version: '3.2'
services:
  sq-report-service:
#    container_name:  "sq-report-service"
    build:
      context: .
      dockerfile: Dockerfile
    image: report-service:latest
    network_mode: host
    environment:
     - NODE_ENV=dev
#    command: sh ./docker-start.sh
#    environment:
#     - NODE_ENV=dev
#    volumes:
#      - .:/var/www
#      - /var/www/node_modules
#    ports:
#      - "3033:3033"
#    network_mode: host
#define network
#networks:
#  default:
#    driver: bridge